apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    name: work-queue
    component: queue
    chapter: jobs
spec:
  selector:
    name: work-queue
    component: queue
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
